version: "3.9"

services:
  db:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wotrdb
      SPRING_DATASOURCE_USERNAME: wotr
      SPRING_DATASOURCE_PASSWORD: admin
    volumes:
       - ./backend:/app

  frontend:
    ports:
      - "3000:80"
     volumes:
       - ./frontend:/usr/share/nginx/html

  caddy:
    profiles: ["caddy-disabled"]
