version: "3.9"

services:
  db:
    image: postgres:16
    container_name: wotr-atlas
    restart: always
    environment:
      POSTGRES_USER: wotr
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wotrdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
