services:
  caddy:
    environment:
      SITE: ${SITE:-:80}
      BACKEND_UPSTREAM: ${BACKEND_UPSTREAM:-host.docker.internal:8080}
      FRONTEND_UPSTREAM: ${FRONTEND_UPSTREAM:-host.docker.internal:4200}
      ACME_EMAIL: ${ACME_EMAIL:-dev@example.com}
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on: []
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    ports: []

  backend:
    ports: []
    environment: {}

  db:
    ports:
      - "5432:5432"
