INSERT INTO factions (code, display_name, banner, capital_waypoint, lord_name)
VALUES
  ('AENURIN', 'Aenurin', 'aenurin', 'shiningPort', NULL),
  ('ANGMAR', 'Angmar', 'angmar', 'CARN_DUM', NULL),
  ('AR_ADUNAIM', 'Ar-adunaim', 'ar-adunaim', 'darkhaven', NULL),
  ('AVARI', 'Avari', 'avari', 'trevaari', NULL),
  ('BLACKLOCKS', 'Wicked Dwarves', 'wicked_dwarves', 'burnedMansion', NULL),
  ('BLUE_MOUNTAINS', 'Blue Mountain Dwarves', 'blue_mountains', 'BELEGOST', NULL),
  ('BREE', 'Bree', 'bree', 'BREE', NULL),
  ('CARDOLAN', 'Cardolan', 'cardolan', 'ruinedCardolan', NULL),
  ('CERINRIM', 'Cerinrim', 'cerinrim', 'mazantsi', NULL),
  ('DALE', 'Dale', 'dale', 'DALE_CITY', NULL),
  ('DOL_GULDUR', 'Dol Guldur', 'dol_guldur', 'DOL_GULDUR', NULL),
  ('DORWINION', 'Dorwinion', 'dorwinion', 'DORWINION_PORT', NULL),
  ('DRUEDAIN', 'Druedain', 'druedain', 'EILENACH', NULL),
  ('DUNLAND', 'Dunland', 'dunland', 'NORTH_DUNLAND', NULL),
  ('DURINS_FOLK', 'Durin''s Folk', 'durin', 'EAST_PEAK', NULL),
  ('EREBOR', 'Erebor', 'erebor', 'EREBOR', NULL),
  ('EREGION', 'Eregion', 'eregion', 'OST_IN_EDHIL', NULL),
  ('FANGORN', 'Fangorn', 'fangorn', 'TREEBEARD_HILL', NULL),
  ('FOROCHEL_ORC', 'Forochel Orcs', 'forochel_orcs', 'fatoftKul', NULL),
  ('GONDOR', 'Gondor', 'gondor', 'MINAS_TIRITH', NULL),
  ('GUNDABAD', 'Gundabad', 'gundabad', 'MOUNT_GUNDABAD', NULL),
  ('HALF_TROLL', 'Half-trolls', 'half_troll', 'gorrind', NULL),
  ('HARAD_DWARF', 'Harad Dwarves', 'harad_dwarf', 'MOUNT_SAND', NULL),
  ('HIGH_ELF', 'High Elves', 'high_elf', 'AMON_EREB', NULL),
  ('HOBBIT', 'Hobbit', 'hobbit', 'MICHEL_DELVING', NULL),
  ('ISENGARD', 'Isengard', 'isengard', 'ISENGARD', NULL),
  ('JINZHUN', 'Jinzhun', 'jinzhun', 'inzhuun', NULL),
  ('KARAVALI', 'Karavali', 'karavali', 'khera', NULL),
  ('KHAND', 'Khand', 'khand', 'bekElma', NULL),
  ('KHAZAD_DUM', 'Khazad-dum', 'khazad_dum', 'MOUNT_CARADHRAS', NULL),
  ('LIMWAITH', 'Limwaith', 'limwaith', 'ikkilAht', NULL),
  ('LOGATHRIM', 'Logathrim', 'logath', 'minasseHatal', NULL),
  ('LOSSOTH', 'Lossoth', 'lossoth', 'helcaMinasse', NULL),
  ('LOTHLORIEN', 'Lothlorien', 'lothlorien', 'CARAS_GALADHON', NULL),
  ('MAHUDUIN', 'Mahuduin', 'mahuduin', 'haudhShivajine', NULL),
  ('MEN_OF_ANDUIN', 'Men of Anduin', 'men_of_anduin', 'OLD_FORD', NULL),
  ('MORDOR', 'Mordor', 'mordor', 'BARAD_DUR', NULL),
  ('MORTAURRI', 'Mortaurri', 'mortauri', 'ivienu', NULL),
  ('MORWAITH', 'Morwaith', 'morwaith', 'GREAT_PLAINS_EAST', NULL),
  ('NEAR_HARAD', 'Near Harad', 'near_harad', 'FERTILE_VALLEY', NULL),
  ('NGOAIRU', 'N''goairu', 'ngoairu', 'ngoai', NULL),
  ('OROCARNI', 'Orocarni', 'orocarni', 'BARAZ_DUM', NULL),
  ('PARALIAKOS', 'Paraliakos', 'paraliakos', 'liakoIslands', NULL),
  ('PROSHYVIL', 'PROSHYVIL', 'PROSHYVIL', 'grondyvil', NULL),
  ('QASINADRIM', 'Qasinadrim', 'qasinadrim', 'hallasholm', NULL),
  ('RANGER_NORTH', 'Dunedain Rangers', 'dunedain_ranger', 'theAngle', NULL),
  ('RHUDEL', 'Rhudel', 'rhudel', 'RHUN_CAPITAL', NULL),
  ('ROHAN', 'Rohan', 'rohan', 'EDORAS', NULL),
  ('STONEFOOTS', 'Stonefoots', 'stonefoots', 'regno', NULL),
  ('TAITAE', 'Ta''itae', 'taitae', 'myaotyk', NULL),
  ('TAIYOBU', 'Taiyobu', 'taiyobu', 'korotoyo', NULL),
  ('TAURETHRIM', 'Taurethrim', 'taurethrim', 'JUNGLE_CITY_CAPITAL', NULL),
  ('UDDARI', 'Uddari', 'uddari', 'saurrung', NULL),
  ('VARILLESRA', 'Varillesra', 'varillesra', 'paramakudi', NULL),
  ('VSEGO', 'Vsego', 'vsego', 'jinalOrn', NULL),
  ('WOOD_ELF', 'Woodland Realm', 'WOOD_ELF', 'THRANDUIL_HALLS', NULL)
ON CONFLICT (code) DO NOTHING;
