INSERT INTO realms (code, display_name, banner, capital_waypoint)
VALUES
  ('AdornlandMan', 'Adornland', 'adornland', 'FRECA_HOLD'),
  ('AenurinMan', 'Aenurin', 'aenurin', 'shiningPort'),
  ('AndrastMan', 'Andrast', 'andrast', 'cairAndrast'),
  ('AnduinMan', 'Anduin', 'men_of_anduin', 'OLD_FORD'),
  ('AnfalasMan', 'Anfalas', 'anfalas', 'portOfLangordui'),
  ('AngmarOrc', 'Angmar', 'angmar', 'CARN_DUM'),
  ('AnorienMan', 'Anorien', 'anorien', 'CAIR_ANDROS'),
  ('ArAdunaimMan', 'Ar-adunaim', 'ar-adunaim', 'darkhaven'),
  ('AvariElf', 'Avari', 'avari', 'trevaari'),
  ('BagginsHobbit', 'Baggins', 'baggins', 'HOBBITON'),
  ('BalchothMan', 'Balchoth', 'balchoth', 'burzRoth'),
  ('Beorning', 'Beorning', 'beorning', 'BEORN'),
  ('BlackrootValeMan', 'Blackroot Vale', 'blackroot_vale', 'ERECH'),
  ('BlackUruk', 'Black Uruks', 'black_uruk', 'SEREGOST'),
  ('BlueDwarf', 'Blue Mountains', 'blue_mountains', 'BELEGOST'),
  ('BreeHobbit', 'Bree Hobbits', 'breehobbit', 'STADDLE'),
  ('BreeMan', 'Bree Men', 'bree', 'BREE'),
  ('BroadbeamsDwarf', 'Broadbeams', 'broadbeams', 'THRAIN_HALLS'),
  ('BucklandHobbit', 'Buckland', 'buckland', 'BUCKLEBURY'),
  ('CardolanMan', 'Cardolan', 'cardolan', 'ruinedCardolan'),
  ('CerinrimMan', 'Cerinrim', 'cerinrim', 'mazantsi'),
  ('ChelkarMan', 'Chelkar', 'chelkar', 'chelherem'),
  ('CoastSouthronMan', 'Coast Southron', 'near_harad', 'FERTILE_VALLEY'),
  ('CorsairOfUmbar', 'Corsair', 'corsair', 'azzatar'),
  ('CuivienenElf', 'Cuivienen', 'cuivienen', 'cuivanari'),
  ('DaleMan', 'Dale', 'dale', 'DALE_CITY'),
  ('DolAmrothMan', 'Dol Amroth', 'dol_amroth', 'DOL_AMROTH'),
  ('DolGuldurOrc', 'Dol Guldur', 'dol_guldur', 'DOL_GULDUR'),
  ('DorwinionElf', 'Dorwinion Elves', 'dorwinion', 'DORWINION_PORT'),
  ('DorwinionMan', 'Dorwinion', 'dorwinion', 'DORWINION_COURT'),
  ('DruedainMan', 'Druedain', 'druedain', 'EILENACH'),
  ('DruethirrimMan', 'Druethirrim', 'druethirrim', 'MOUTHS_ISEN'),
  ('DruwaithIaurMan', 'Druwaith Iaur', 'druwaithiaur', 'jurraur'),
  ('DunedainRanger', 'Dunedain', 'dunedain_ranger', 'theAngle'),
  ('DunharrowMan', 'Dunharrow', 'dunharrow', 'DUNHARROW'),
  ('DunlandMan', 'Dunland', 'dunland', 'NORTH_DUNLAND'),
  ('EastemnetMan', 'Eastemnet', 'eastemnet', 'EASTMARK'),
  ('EasternDesolationUruk', 'Desolation Uruks', 'desolation_uruk', 'rothKatund'),
  ('EastfoldMan', 'Eastfold', 'rohan', 'EDORAS'),
  ('ElvenWanderer', 'Elven Wanderers', 'elven_wanderer', 'OLD_ELF_WAY'),
  ('EnedwaithMan', 'Enedwaith', 'enedwaith', 'ostduunarath'),
  ('EreborDwarf', 'Erebor', 'erebor', 'EREBOR'),
  ('EregionElf', 'Eregion', 'eregion', 'OST_IN_EDHIL'),
  ('FangornEnt', 'Fangorn', 'fangorn', 'TREEBEARD_HILL'),
  ('ForochelOrc', 'Forochel Orcs', 'forochel_orcs', 'fatoftKul'),
  ('GondorMan', 'Gondor', 'gondor', 'MINAS_TIRITH'),
  ('GreenwoodElf', 'Greenwood Elves', 'greenwood_elves', 'emynLum'),
  ('GulfSouthronMan', 'Gulfing Southrons', 'harad_gulf', 'GULF_CITY'),
  ('GundabadOrc', 'Gundabad Orcs', 'gundabad', 'SCATHA'),
  ('GundabadUruk', 'Gundabad Uruks', 'gundabad', 'MOUNT_GUNDABAD'),
  ('HalfTroll', 'Half-trolls', 'half_troll', 'gorrind'),
  ('HaradDwarf', 'Harad Dwarves', 'harad_dwarf', 'MOUNT_SAND'),
  ('HaradNomad', 'Harad Nomads', 'harad_nomad', 'dunesOfTheGreatDesert'),
  ('HarlindonElf', 'Harlindon', 'harlindon', 'HARLOND'),
  ('HarnennorMan', 'Harnennor', 'harnennor', 'HARNEN_SEA_TOWN'),
  ('HarondorMan', 'Harondor', 'harondor', 'nallarin'),
  ('IronfistsDwarf', 'Ironfists', 'ironfists', 'khagaldrim'),
  ('IronHillsDwarf', 'Iron Hills', 'durin', 'EAST_PEAK'),
  ('IsengardUruk', 'Isengard', 'isengard', 'ISENGARD'),
  ('IthilienRanger', 'Ithilien', 'ithilien', 'HENNETH_ANNUN'),
  ('JinzhunMan', 'Jinzhun', 'jinzhun', 'inzhuun'),
  ('KaranolaMan', 'Karanola', 'karanola', 'rhunnaran'),
  ('KaravaliMan', 'Karavali', 'karavali', 'khera'),
  ('KhandMan', 'Khand', 'khand', 'bekElma'),
  ('KhazadDumDwarf', 'Khazad-dum', 'khazad_dum', 'MOUNT_CARADHRAS'),
  ('LamedonMan', 'Lamedon', 'lamedon', 'CALEMBEL'),
  ('LebenninMan', 'Lebennin', 'lebennin', 'ostgondhir'),
  ('LhugathMan', 'Lhugath', 'lhugath', 'minasseHatal'),
  ('LimwaithMan', 'Limwaith', 'limwaith', 'ikkilAht'),
  ('LindonElf', 'Lindon', 'high_elf', 'AMON_EREB'),
  ('LogathMan', 'Logath', 'logath', 'cofFervain'),
  ('LonelandsRanger', 'Lone-lands', 'lone_lands', 'WEATHERTOP'),
  ('LossarnachMan', 'Lossarnach', 'lossarnach', 'IMLOTH_MELUI'),
  ('LossothMan', 'Lossoth', 'lossoth', 'helcaMinasse'),
  ('LothlorienElf', 'Lothlorien', 'lothlorien', 'CARAS_GALADHON'),
  ('LuneValleyMan', 'Lune Valley', 'lune_valley', 'lhunPort'),
  ('MahuduinMan', 'Mahuduin', 'mahuduin', 'haudhShivajine'),
  ('MirkUruk', 'Mirk-uruks', 'mirk_uruk', 'anugMaudhol'),
  ('MirkwoodHunter', 'Mirkwood Hunters', 'mirkwood_hunter', 'MIRKWOOD_MOUNTAINS'),
  ('MistyMountainsGoblin', 'Misty Goblins', 'misty_goblins', 'GOBLIN_TOWN'),
  ('MithlondElf', 'Mithlond', 'mithlond', 'MITHLOND_NORTH'),
  ('MolraeenMan', 'Molraeen', 'molraeen', 'molrae'),
  ('MordorOrc', 'Mordor', 'mordor', 'BARAD_DUR'),
  ('MorgaiOrc', 'Morgai', 'morgai', 'DURTHANG'),
  ('MorgulValeOrc', 'Morgul Vale', 'minas_morgul', 'MINAS_MORGUL'),
  ('MortaurriElf', 'Mortaurri', 'mortauri', 'ivienu'),
  ('MorthondMan', 'Morthond', 'morthond', 'galenhelm'),
  ('MorwaithMan', 'Morwaith', 'morwaith', 'GREAT_PLAINS_EAST'),
  ('NanUngolOrc', 'Nan Ungol', 'nan_ungol', 'VALLEY_OF_SPIDERS'),
  ('NgoairuMan', 'N''goairu', 'ngoairu', 'ngoai'),
  ('NuriagMan', 'Nuriag', 'nuriag', 'utotNuriag'),
  ('NurnOrc', 'Nurn', 'nurn_orc', 'THAURBAND'),
  ('OrocarniDwarf', 'Orocarni', 'orocarni', 'BARAZ_DUM'),
  ('ParaliakosMan', 'Paraliakos', 'paraliakos', 'liakoIslands'),
  ('PelargirMan', 'Pelargir', 'pelargir', 'PELARGIR'),
  ('PinnathGelinMan', 'Pinnath Gelin', 'pinnath_gelin', 'GREEN_HILLS'),
  ('ProshloyeMan', 'Proshyvil', 'proshyvil', 'grondyvil'),
  ('QasinadrimMan', 'Qasinadrim', 'qasinadrim', 'hallasholm'),
  ('RhovanionMan', 'Rhovanion', 'rhovanion', 'opeleRhovanion'),
  ('RhudaurHillman', 'Rhudaur', 'rhudaur', 'rhudaurnor'),
  ('RhudelMan', 'Rhudel', 'rhudel', 'RHUN_CAPITAL'),
  ('RingloValeMan', 'Ringlo Vale', 'ringlo_vale', 'nendahil'),
  ('RivendellElf', 'Rivendell', 'rivendell', 'RIVENDELL'),
  ('RuboorMan', 'Ruboor', 'ruboor', 'theRubooryMansion'),
  ('SargathMan', 'Sargath', 'sargath', 'theRedFord'),
  ('ShireHobbit', 'Shire', 'hobbit', 'MICHEL_DELVING'),
  ('SindarElf', 'Sindar', 'sindar', 'TOL_FUIN'),
  ('StonefootDwarf', 'Stonefoots', 'stonefoots', 'regno'),
  ('SyyranniMan', 'Syyranni', 'syyranni', 'arniOrTora'),
  ('TaitaeDwarf', 'Ta''itae Dwarves', 'taitae', 'cajjion'),
  ('TaitaeMan', 'Ta''itae', 'taitae', 'myaotyk'),
  ('TaiyobuMan', 'Taiyobu', 'taiyobu', 'korotoyo'),
  ('TaurethrimMan', 'Taurethrim', 'taurethrim', 'JUNGLE_CITY_CAPITAL'),
  ('ThoronriMan', 'Thoronri', 'thoronri', 'JUNGLE_CITY_TRADE'),
  ('TookHobbit', 'Took', 'took', 'TUCKBOROUGH'),
  ('UddariMan', 'Uddari', 'uddari', 'saurrung'),
  ('UmbarMan', 'Umbar', 'umbar', 'UMBAR_CITY'),
  ('UsrakinMan', 'Usrakin', 'usrakin', 'tsama'),
  ('VarillesraDwarf', 'Varillesra', 'varillesra', 'paramakudi'),
  ('VsegoMan', 'Vsego', 'vsego', 'jinalOrn'),
  ('WainriderMan', 'Wainriders', 'wainriders', 'BALCARAS'),
  ('WestemnetMan', 'Westemnet', 'westemnet', 'flodgeheld'),
  ('WestfoldMan', 'Westfold', 'westfold', 'HELMS_DEEP'),
  ('WickedDwarf', 'Wicked Dwarves', 'wicked_dwarves', 'burnedMansion'),
  ('WoldMan', 'Wold', 'wold', 'WOLD'),
  ('WoodlandRealmElf', 'Woodland Realm', 'WOOD_ELF', 'THRANDUIL_HALLS'),
  ('ZunimlothMan', 'Zunimloth', 'zunimloth', 'mupata')
ON CONFLICT (code) DO NOTHING;
