-- Waypoints (lightweight, no triggers)
CREATE TABLE IF NOT EXISTS waypoints (
  code          TEXT PRIMARY KEY,
  display_name  TEXT,
  realm_code    TEXT NOT NULL REFERENCES realms(code) ON DELETE RESTRICT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed waypoints
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('abianjian','Abianjian','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('aearon','Aearon','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('AIN_AL_HARAD','Ain an-Ahâr','CoastSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('aireTuile','Airë-Tuilë','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ajlion','Ajlion','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('akasmanai','Akasmanai','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('akktayron','Akktayron','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ALDBURG','Aldburg','EastfoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('alpinan','Alpinan','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('alsati','Alsati','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ambred','Ambre''d','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('amled','Amled','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ammiavaPass','Ammiava Pass','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('AMON_ANGREN','Amon Angren','BlackUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('AMON_DIN','Amon Dîn','AnorienMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('AMON_EREB','Amon Ereb','LindonElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('AMON_HEN','Amon Hen','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('AMON_LHAW','Amon Lhaw','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ancaAht','Anca-Aht','LimwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('andoMacar','Ando-Macar','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('andrathForests','Andrath Forests','DunedainRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ANDUIN_CROSSROADS','Crossroads of Anduin','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ANDUIN_MOUTH','Ethir Anduin','LebenninMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('angmarPlains','Angmar Plains','AngmarOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ANNUMINAS','Annúminas','DunedainRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('antazylan','Antazylan','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('anugMaudhol','Anug Maudhol','MirkUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('araayn','Araayn','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('arakanunai','Arakanunai','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('aranbad','Aranbad','CardolanMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('arataNasse','Arata-nassë','GundabadOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('araxitt','Araxitt','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ARCHET','Archet','BreeHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ardarog','Ardarog','HalfTroll');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('arearni','Arearni','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ARGONATH','Argonath','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('arJaless','Ar-jaless','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('arngonost','Arngonost','AnfalasMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('arniOrTora','Arni Or Tora','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('arralan','Arralan','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('arthedain','Arthedain','DunedainRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ARVEDUI_MINES','Arvedui''s Mines','BlueDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ashya','Ash''ya','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('atalitai','Atalitai','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('azunacar','Azunacar','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('azunrNalim','Azunr Nalim','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('azzatar','Azzatar','CorsairOfUmbar');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('baikarsPass','Baikars Pass','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BALCARAS','Balcharas','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('balgasBuyanbak','Balgas Buyan''bak','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BARAD_DUR','Barad-dûr','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('baradAmrun','Barad-Amrun','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('baradCanas','Barad-Canas','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('baradHelch','Barad-Helch','SargathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('baradHeneb','Barad Heneb','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BARAZ_DUM','Baraz-tûm','OrocarniDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('barlanas','Barlanas','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('barnurnen','Barnurnen','NurnOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('bazianti','Bazianti','ArAdunaimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BAZYLAN','Bazylan','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('bekElma','Bek-Elma','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BELEGOST','Belegost','BlueDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BEORN','Beorn''s Hall','Beorning');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('berenstil','Berenstil','CardolanMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('berrontu','Berrontu','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BLACK_COAST','Durfalas','HalfTroll');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BLOOD_RIVER','Sereghir','HalfTroll');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('borapeli','Borapeli','UsrakinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BORDER_TOWN','Taragal','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('borteenPort','Borteen Port','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('bortenfor','Bortenfor','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BRANDYWINE_BRIDGE','Brandywine Bridge','BucklandHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BREE','Bree','BreeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('broadacres','Broadacres','WestemnetMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('broadbeamsMansions','Broadbeams Mansions','BroadbeamsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BROCKENBORINGS','Brockenborings','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('brondost','Brondost','DolAmrothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('bruntin','Bruntin','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('brysCam','Brys Cam','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BUCKLEBURY','Bucklebury','BucklandHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('burguulDur','Burguul-Dur','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('burnedMansion','Burned Mansion','WickedDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('burzRoth','Burz-roth','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('BYWATER','Bywater','BagginsHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('cahatontu','Cahatontu','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CAIR_ANDROS','Cair Andros','AnorienMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('cairAndrast','Cair Andrast','AndrastMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('cajjion','Cajjion','TaitaeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('calarIrin','Calar-Irin','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CALEMBEL','Calembel','LamedonMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CALENHAD','Calenhad','AnorienMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('canhong','Canhong','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CAPE_OF_FOROCHEL','Cape of Forochel','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CARACH_ANGREN','Carach Angren','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CARAS_GALADHON','Caras Galadhon','LothlorienElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('carasTilion','Caras Tilion','WoodlandRealmElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CARN_DUM','Carn Dûm','AngmarOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CARROCK','Carrock','Beorning');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('cayleo','Cayleo','UddariMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CEDAR_ROAD','Cedar-woods','CoastSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CERIN_AMROTH','Cerin Amroth','LothlorienElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ceuranCar','Ceuran-Car','AvariElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('chatran','Chatran','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('chelherem','Chelherem','ChelkarMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('chimiri','Chimiri','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('chorisVale','Choris Vale','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('chorron','Chorron','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('chyYhyTan','Chy Yhy Tan','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CIRITH_UNGOL','Cirith Ungol','MorgulValeOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('COAST_CITY','Nurêmin','CoastSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('COAST_FORTRESS','Gâth-azrazâin','CoastSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('COAST_RIVER_TOWN','Tawînen','CoastSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('cofFervain','Côf-Fervain','LogathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('COMBE','Combe','BreeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('corma','Corma','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CORSAIRS_LANDING','Corsair''s Landing','AdornlandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CROSSINGS_ERUI','Crossings of Erui','LossarnachMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CROSSINGS_OF_HARAD','Crossings of Harnen','HarnennorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CROSSINGS_OF_LITHNEN','Crossings of Lithnen','HarnennorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CROSSINGS_OF_POROS','Crossings of Poros','IthilienRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('CROSSROADS_ITHILIEN','Crossroads of the Fallen King','IthilienRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('crossroadsOfFire','Crossroads of Fire','HalfTroll');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('crossroadsOfHael','Crossroads of Hael','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('crossroadsOfJaaka','Crossroads of Jaaka','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('cuivanari','Cuivarnari','CuivienenElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('cuuli','Cuuli','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('daeCanas','Dae-Canas','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DAINS_HALLS','Dáin''s Halls','EreborDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DALE_CITY','Dale','DaleMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DALE_CROSSROADS','Great Dalish Crossroads','DaleMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DALE_PORT','Bardhaven','DaleMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dalonra','Dalonra','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('darantan','Darantan','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('daravajo','Daravajo','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dargum','Dargum','NuriagMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('darkhaven','Darkhaven','ArAdunaimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('darvari','Darvari','MortaurriElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DEEPHALLOW','Deephallow','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('deepingForest','Deeping Forest','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DERNDINGLE','Derndingle','FangornEnt');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DESERT_RIVER_TOWN','Ayûkaph-amâm','HaradNomad');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DESERT_TOWN','Ijdi-ilel','HaradNomad');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('diialond','Diialond','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DIMRILL_DALE','Dimrill Dale','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dingxai','Dingxai','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dinyana','Dinyana','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('doantoi','Doantoi','UddariMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dofnIrin','Dofn-Irin','LhugathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dohoyonu','Dohoyonu','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DOL_AMROTH','Dol Amroth','DolAmrothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DOL_GULDUR','Dol Guldur','DolGuldurOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('doniorra','Doniorra','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('doommor','Doomoor','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dorazPorandum','Doraz Porandum','NuriagMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DORWINION_COURT','Vintner Court','DorwinionMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DORWINION_CROSSROADS','Dorwinion Crossroads','DorwinionMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DORWINION_FORD','Golden Ford','DorwinionMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DORWINION_HILLS','Amon Gwîn','DorwinionElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DORWINION_PORT','Mirulond','DorwinionElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('drathalta','Drathalta','MirkUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('drownholt','Drownholt','MirkwoodHunter');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dundayron','Dundayron','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dunesOfTheGreatDesert','Dunes of the Great Desert','HaradNomad');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DUNHARROW','Dunharrow','DunharrowMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DURTHANG','Durthang','MorgaiOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('duurdarri','Duurdarri','UddariMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('DWARROWVALE','Dwarrowvale','DunlandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('dypsklng','Dypsklng','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EAGLES_EYRIE','Eagles'' Eyrie','Beorning');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('eamoru','Eamoru','UsrakinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EAST_BIGHT','East Bight','MirkUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EAST_PEAK','Central Peak','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EAST_RHOVANION_ROAD','East Rhovanion Gate','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EASTERN_GUARD','Eastern Guard','EasternDesolationUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('eastGate','East Gate','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('eastGateOfMoria','East Gate of Moria','MistyMountainsGoblin');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EASTMARK','Eastmark','EastemnetMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('eavesLanding','Eave''s Landing','LothlorienElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('echedorgor','Echedorgor','EnedwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('edennen','Edennen','LebenninMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EDHELLOND','Edhellond','DolAmrothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EDORAS','Edoras','EastfoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EILENACH','Eilenach','DruedainMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('eithelarin','Eithelarin','HarnennorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('emeraldPeaks','Emerald Peaks','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('emtarnadrin','Em-tarnadrin','KaranolaMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('emumGol','Emum Gol','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EMYN_ARNEN','Emyn Arnen','IthilienRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('emynLum','Emyn Lum','GreenwoodElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('emynNuFuin','Emyn Nu Fuin','MirkwoodHunter');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('emynTirin','Emyn Tirin','AnfalasMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ENCHANTED_RIVER','Enchanted River','WoodlandRealmElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('enedCoast','Ened Coast','DruethirrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ENEDWAITH_ROAD','Old South Road','EnedwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('engrinVale','Engrin Vale','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('engrionra','Engrionra','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ennorooh','Ennorooh','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ENTWADE','Entwade','WestemnetMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('erCen','Er Cen','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('EREBOR','Erebor','EreborDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ERECH','Erech','BlackrootValeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('erechosdur','Erechosdur','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ERELAS','Erelas','AnorienMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('erumemar','Erumëmar','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ERYN_VORN','Eryn Vorn','CardolanMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('esMuna','Es-Muna','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('esseNorda','Esse Norda','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ETHRING','Ethring','LamedonMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ettenmoors','Ettenmoors','AngmarOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('faihen','Faihen','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('fatoftKul','Fatoft-Kul','ForochelOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('feizhu','Feizhu','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('felegoth','Felegoth','WoodlandRealmElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FELLBEASTS','Vale of the Fell Beasts','BlackUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('fellLeaf','Fell-leaf','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FERTILE_VALLEY','Ajtiaz an-Ahâr','CoastSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('fervainBarad','Fervain-Barad','LhugathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FIELD_OF_CELEBRANT','Field of Celebrant','LothlorienElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('flodand','Flodänd','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('flodgeheld','Flodgeheld','WestemnetMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FORD_BRUINEN','Ford of Bruinen','RivendellElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FORDS_OF_ISEN','Fords of Isen','DunlandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FOREST_GATE','Forest Gate','GreenwoodElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('forestRiver','Forest River','WoodlandRealmElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FORLINDON','Forlindon','LindonElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FORLOND','Forlond','LindonElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('forlondWoodlands','Forlond Woodlands','LindonElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FORNOST','Fornost','LonelandsRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('forochelGate','Forochel Gate','ForochelOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('forodwaithMountains','Forodwaith Mountains','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FORSAKEN_INN','Forsaken Inn','BreeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FRAMSBURG','Framsburg','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FRECA_HOLD','Freca''s Hold','AdornlandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('FROGMORTON','Frogmorton','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('frondorith','Frondorith','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('galadEregion','Galad Eregion','EregionElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('galenhelm','Galenhelm','MorthondMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('galuBar','Galu-Bâr','LhugathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GARDENS_BERUTHIEL','Gardens of Barûphel','CoastSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('garthring','Garthring','AnfalasMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GATE_FUINUR','Anât an-Phôinûr','CoastSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GATE_HERUMOR','Anât an-Khôrumor','UmbarMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('gazBurGuldur','Gas Bur Guldur','DolGuldurOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('gedhim','Gedhim','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ghunumHalk','Ghunum Halk','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('giyuang','Giyuang','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GLADDEN_FIELDS','Gladden Confluence','LothlorienElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('gladdenSprings','Gladden Springs','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('glaidIrin','Glaid-Irin','LhugathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('glamhold','Glamhold','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GOBLIN_TOWN','Goblin Town','MistyMountainsGoblin');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('goobaty','Goobaty','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('gorrind','Gorrind','HalfTroll');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('gostalak','Gostalak','KaranolaMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('goudarr','Goudarr','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('graveyardOfDagorlad','Graveyard of Dagorlad','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GREAT_PLAINS_EAST','Hill of the Sun','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GREAT_PLAINS_NORTH','Hunters'' Haunt','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GREAT_PLAINS_SOUTH','Deep Harad','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GREAT_PLAINS_WEST','Upper Floodplains','MolraeenMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GREEN_HILLS','Pinnath Gelin','PinnathGelinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GREEN_VALLEY','Nan Harnagorath','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GREENHOLM','Greenholm','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GREENWAY_CROSSROADS','Greenway Crossroads','BreeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('grimbeornsHall','Grimbeorn''s Hall','Beorning');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GRIMSLADE','Grimslade','WestfoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('grodgrim','Grodgrim','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('grondyvil','Grondyvil','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('guingi','Guin-gi','TaitaeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GULF_CITY','Khôpakadar','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GULF_EAST_BAY','Topaz Bay','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GULF_EAST_PORT','Ephalôn','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GULF_FORD','Bridge of Harlanhir','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GULF_NORTH_TOWN','Yaphurushi','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GULF_OF_HARAD','Arminazûl','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('GULF_TRADE_TOWN','Bakrîzad','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('gulroon','Gulroon','NanUngolOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('guuduror','Guuduror','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('gwaerenni','Gwaerenni','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('gwainIrin','Gwain-Irin','SargathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('haellea','Haellea','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('halaAht','Hala-Aht','LimwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('halaIrin','Hala-Irin','LogathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('halcinLake','Halcin Lake','ForochelOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HALIFIRIEN','Halifirien','AnorienMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hallasholm','Hallasholm','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('halvo','Halvö','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hangye','Hangye','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARAD_HORN','Horn of Harad','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARAD_LAKES','Nin Haecharad','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('haradRoad','Harad Road','HarondorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARADUIN_BRIDGE','Bridge of Haraduin','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARADUIN_MOUTH','Ethir Haraduin','LimwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('haralake','Haralake','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('harlanni','Harlanni','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARLINDON','Harlindon','HarlindonElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('harlindonForests','Harlindon Forests','HarlindonElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARLOND','Harlond','HarlindonElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARNEN_BLACK_TOWN','Ugrî-zadîn','HarnennorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARNEN_RIVER_TOWN','Ninzadîn','HarnennorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARNEN_ROAD_TOWN','An-batîna','HarnennorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HARNEN_SEA_TOWN','Bêlkadar','HarnennorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hartarast','Hartarast','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('harwick','Harwick','WoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('haudhShivajine','Haudh Shivajine','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HAY_GATE','Hay Gate','BucklandHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HAYSEND','Haysend','BucklandHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('helcaMinasse','Helca-Minassë','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HELMS_CROSSROADS','Deeping-coomb','WestfoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HELMS_DEEP','Helm''s Deep','WestfoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HENNETH_ANNUN','Henneth Annûn','IthilienRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('herrade','Herrade','HaradNomad');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HIGH_PASS','High Pass','MistyMountainsGoblin');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('highlands','Eriador Highlands','LuneValleyMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('highMoor','High Moor','ElvenWanderer');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HIMLING','Himling','SindarElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('HOBBITON','Hobbiton','BagginsHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hodarritor','Hodarritor','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hoobYat','Hoob-yat','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hopaIrin','Hopa-irin','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hornOfForochel','Horn of Forochel','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hornOfUmbar','Horn of Umbar','UmbarMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hossith','Hossith','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hralrick','Hralrick','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('hubCanas','Hûb-Canas','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('iaurOnni','Iaur Onni','DruwaithIaurMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ibbror','Ibbror','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ichibi','Ichibi','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ikkilAht','Ikkil-Aht','LimwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ilenna','Ilenna','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('illskaDur','Illska-Dur','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('IMLOTH_MELUI','Imloth Melui','LossarnachMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('indlufa','Indlufa','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('inqaba','Inqaba','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('inqqi','Inqqi','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('inzhuun','Inzhuun','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ippurril','Ippurril','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('irinTaurina','Irin-Taurina','LogathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ISENGARD','Isengard','IsengardUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ISLE_MIST','Tol Hîth','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ittraPort','Ittra Port','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ivienu','Ivienu','MortaurriElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jaakapurra','Jaakapurra','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jaarak','Jaarak','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('janoloba','Janoloba','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('japurmurti','Japurmurti','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jarinHall','Jarin Hall','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jendiar','Jendiar','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jhankian','Jhankian','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jinalOrn','Jinal-orn','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jinorocarn','lotr.waypoint.jinorocarn','IronfistsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jionour','Jionour','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_CITY_CAPITAL','Nohoch Kâh','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_CITY_CAVES','Aktun Kâh','ThoronriMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_CITY_DEEP','Mûmakâh','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_CITY_EAST','Lakin Pâh','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_CITY_NORTH','Shaman Pâh','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_CITY_OLD','Ya''ash Kâh','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_CITY_STONE','Tûnich Kâh','ThoronriMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_CITY_TRADE','Otoch Kâh','ThoronriMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_CITY_WATCH','Pishan Kâh','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('JUNGLE_LAKES','Emerald Lakes','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jurraur','Jurraur','DruwaithIaurMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('jussarnu','Jussarnu','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kaaparakhendra','Kaaparakhendra','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kadda','Kadda','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kafakUnaz','Kafak-Unaz','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kaivathroxosina','Kaivathroxosina','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kallkork','Kallkork','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kamashiwu','Kamashiwu','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kanukarri','Kanukarri','UsrakinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('karuwua','Karuwua','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('katund','Katund','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ketelImi','Ketel-Imi','EasternDesolationUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kevlan','Kevlan','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kezayo','Kezayo','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kezbe','Kezbe','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('khagaldrim','Khagal-drim','IronfistsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('KHAMUL_TOWER','Khamûl''s Tower','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('KHAND_FORD','Khandwater Ford','ChelkarMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('KHAND_NORTH_ROAD','North Khand Road','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('khangele','Khangele','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kheleOndar','Khele-ondar','LhugathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('khera','Khera','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kheremGol','Kherem Gol','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kheremHall','Kherem Hall','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('khesimKharan','Khesim Kharan','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('khopel','Khopel','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kiarnti','Kiarnti','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kiiji','Kiiji ','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kingsway','Kingsway','ArAdunaimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kirmodo','Kirmodo','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kitai','Kitai','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kitotBalchoth','Kitot Balchoth','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('korotoyo','Korotoyo','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('korysFirstStep','The First','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('korysFourthStep','The Fourth','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('korysSecondStep','The Second','GulfSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('korysThirdStep','The Third','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kraxaar','Kraxaar','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kuloba','Kuloba','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kumurFushaum','Kumur-Fushaum','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kuromatsunai','Kuromatsunai','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('kwedziva','Kwedziva','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('laaralia','Laaralia','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lagoonOfDoron','Lagoon of Doron','HaradNomad');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('LAKE_HARAD','Chunha','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lakeDarrid','Lake Darrid','TaitaeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lakeEvendim','Lake Evendim','DunedainRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lakeOhi','Lake Ohi','MortaurriElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lammak','Lammak','TaitaeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('landaura','Landhaura','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('LAST_BRIDGE','Last Bridge','LonelandsRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lastOasis','Last Oasis','HaradNomad');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lavaralda','Lavaralda','LimwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('leaat','Leaat','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('leputsoa','Leputsoa','UsrakinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lhugahar','Lhugahar','LhugathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lhunPort','Lhun Port','LuneValleyMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('liakoIslands','Liako Islands','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('liannHall','Liann Hall','CardolanMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('LINHIR','Linhir','LebenninMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('LITTLE_DELVING','Little Delving','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('liuyunPort','Liuyun Port','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('loeglond','Laeglond','WoodlandRealmElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('LOND_DAER','Lond Daer','EnedwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('LONG_LAKE','Long Lake','DaleMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('LONGBOTTOM','Longbottom','TookHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('losseMarto','Lossë-Marto','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('losseNasse','Lossë-Nassë','ForochelOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lotash','Lotash','AngmarOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lozani','Lozani','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('loziCliffs','Lozi Cliffs','RuboorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lrindeOndi','Lrinde Ondi','AvariElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('lurinatar','Lurinatar','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('maodza','Maodza','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('marhin','Marhin','LuneValleyMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('marrinhur','Marrinhur','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mastoLoico','Masto Loico','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mazantsi','Mazantsi','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MERING_STREAM','Mering Stream','EastfoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('metsi','Metsi','UsrakinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('miarron','Miarron','AvariElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MICHEL_DELVING','Michel Delving','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MINAS_MORGUL','Minas Morgul','MorgulValeOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MINAS_TIRITH','Minas Tirith','GondorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('minasNumen','Minas Numen','RhovanionMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('minasseHatal','Minassë-Hatal','LhugathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('minasseNosta','Minassë-Nosta','CuivienenElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('minBarad','Mîn-Barad','LhugathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MINRIMMON','Min-Rimmon','AnorienMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mirkeaves','Mirk-eaves','MirkUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MIRKWOOD_MOUNTAINS','Mountains of Mirkwood','MirkwoodHunter');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('miroir','Miroir','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mistyEregion','Misty Eregion','MistyMountainsGoblin');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mithgrim','Mithgrim','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MITHLOND_NORTH','North Mithlond','MithlondElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MITHLOND_SOUTH','South Mithlond','MithlondElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('molrae','Molrae','MolraeenMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('moorstown','Moorstown','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MORANNON','Black Gate','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MORDOR_FORD','Ashen Ford','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('morgaiVale','Morgai Slopes','MorgaiOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MORIGOST','Mornost','MorgaiOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('morooh','Morooh','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('morvarwood','Morvarwood','MortaurriElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_CARADHRAS','Mount Caradhras','KhazadDumDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_CELEBDIL','Mount Celebdil','KhazadDumDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_DOLMED','Mount Dolmed','BlueDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_DOOM','Mount Doom','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_FANUIDHOL','Mount Fanuidhol','KhazadDumDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_GRAM','Mount Gram','GundabadUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_GREEN','Mount Laegras','HaradDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_GUNDABAD','Mount Gundabad','GundabadOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_METHEDRAS','Mount Methedras','MistyMountainsGoblin');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_RERIR','Mount Rerir','BlueDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_SAND','Mount Athras','HaradDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUNT_THUNDER','Mount Belegwaeras','HaradDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mountAngmar','Mount Angmar','AngmarOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mountDonyanya','Mount Donyanya','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mountkhazgrim','Mount Khazgrim','OrocarniDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mountRillira','Mount Rillira','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mountUttor','Mount Uttor','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('MOUTHS_ISEN','Mouths of Isen','DruethirrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mrognyi','Mrognyi','RuboorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mundoIrin','Mundo-Irin','LogathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mupata','Mupata','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('muundarith','Muundarith','SargathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('mvurakanzika','Mvurakanzika','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('myaotyk','Myaotyk','TaitaeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('naeriOnd','Naeri-ond','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('nahitu','Nah-itu','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('nallarin','Nallarin','HarondorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NARDOL','Nardol','AnorienMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NARGROTH','Narroth','BlackUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('narlann','Narlann','UddariMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NEEDLEHOLE','Needlehole','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('neledCel','Neled-Cel','UsrakinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('nendahil','Nendahil','RingloValeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('nerapavarai','Nerapavarai','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('newEastPeak','East Peak','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ngasent','Ngasent','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ngoai','N''goai','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NIMRODEL','House of Nimrodel','LothlorienElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ninqueCorda','Ninquë-Corda','OrocarniDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NOBOTTLE','Nobottle','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('nocisily','Noc Isily','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NOGROD','Nogrod','BlueDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('norcroft','Norcroft','EastemnetMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NORTH_DOWNS','North Downs','LonelandsRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NORTH_DUNLAND','Duneard','DunlandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NORTH_ITHILIEN','North Ithilien','IthilienRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NORTH_UNDEEP','North Undeep','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('northDorwinion','North Dorwinion','DorwinionMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('northernWastes','Northern Wastes','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('northGate','North Gate','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('nostaRanda','Nosta Randa','AvariElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('numenthrimwatchtower','Numenthrim Watch-tower','ArAdunaimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NURNEN_EASTERN_SHORE','Rhunurnen','NurnOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NURNEN_NORTHERN_SHORE','Fornurnen','NurnOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NURNEN_SOUTHERN_SHORE','Harnurnen','NurnOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('NURNEN_WESTERN_SHORE','Dunurnen','NurnOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('OATBARTON','Oatbarton','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('okhtas','Okhtas','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('OLD_ELF_WAY','Old Elven Way','ElvenWanderer');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('OLD_FORD','Old Ford','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('OLD_JUNGLE_RUIN','Kimen Kâh','HalfTroll');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('OLD_RHOVANION','Old Rhovanion','RhovanionMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('oldPelargarth','oldPelargarth','PelargirMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ondalas','Ondalas','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ondarlun','Ondarlun','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ondSirron','Ond-sirron','LonelandsRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('onohi','Onohi','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ontahairem','Onta-hairem','ChelkarMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ontrysil','Ontrysil','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ontturun','Ontturun','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('opeleHala','Opelë-Hala','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('opeleRhovanion','Opelë Rhovanion','RhovanionMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ordGremin','Ord Gremin','MorthondMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ordShar','Ord Shar','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('oroered','Oro-ered','OrocarniDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('orondakhahaz','Orondakhahaz','OrocarniDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('oronoti','Oronoti','AvariElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('orriho','Orriho','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('osforod','Osforod','RhudaurHillman');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('OSGILIATH_EAST','East Osgiliath','IthilienRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('OSGILIATH_WEST','West Osgiliath','GondorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ossiriand','Ossiriand','LindonElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('OST_IN_EDHIL','Ost-in-Edhil','EregionElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ostduunarath','Ost-duunarath','EnedwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ostGelthiod','Ost-Gelthiod','PinnathGelinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ostgondhir','Ost-gondhir','LebenninMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ostgwathil','Ost-gwathil','CardolanMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ostkrag','Ostkrag','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ostoftor','Ostoftor','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('OVERHILL','Overhill','BagginsHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('paramakudi','Paramakudi','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('parantii','Parantii','TaitaeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('parlinTown','Parlin Town','BlackrootValeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('passOfHelko','Pass of Helko','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('passOfZuezhu','Pass of Zuezhu','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('PELARGIR','Pelargir','PelargirMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('philliOpos','Philli Opos','ThoronriMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('portKorTan','Port Kor-Tan','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('portOfFire','Port of Fire','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('portOfLangordui','Port of Langordui','AnfalasMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('prakasa','Prakasa','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('pramud','Pramud','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('prataragrap','Prataragrap','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('pujivada','Pujivada','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('qamlezo','Qamlezo','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('rahavPort','Rahav Port','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('raineHopa','Rainë-Hopa','RuboorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('raksaka','Raksaka','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RAS_MORTHIL','Ras Morthil','AndrastMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RAUROS','Rauros','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ravenhill','Ravenhill','EreborDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('rayusuunIsle','Rayusuun Isle','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('redhall','The Red Hall','OrocarniDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('redSprings','Red Springs','IronfistsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('REDWATER_FORD','Redwater Ford','DaleMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('regno','Regno','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('reorondir','Reorondir','LuneValleyMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('retaKilha','Reta Kilha','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHOSGOBEL','Rhosgobel','AnduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('rhudaurnor','Rhudaurnor','RhudaurHillman');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_CAPITAL','Rhúnost','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_EAST_CITY','Karslan','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_EAST_TOWN','Karanoda','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_NORTH_CITY','Atalak','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_NORTH_FORD','Ford of Forunen','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_NORTHEAST','Northern Marches','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_ROAD_WAY','Redway','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_SEA_CITY','Belrhuk','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_SOUTH_PASS','Pass of Rhúdel','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RHUN_SOUTHEAST','Southern Marches','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('rhunnaran','Rhunnaran','KaranolaMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('rhunocaras','Rhunocaras','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('rindeEldar','Rindë Eldar','AvariElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RIVENDELL','Rivendell','RivendellElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RIVER_GATE','River Gate','WoodlandRealmElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('riverAngren','River Angren','DruethirrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('riverCulurien','River Culurien','AvariElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('riverGilrain','River Gilrain','RingloValeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('riverGwathlo','riverGwathlo','CardolanMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('riverLeen','River Leen','UddariMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('riverLefnui','River Lefnui','AnfalasMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('riverLune','River Lune','LuneValleyMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('riverMitheithel','River Mitheithel','AngmarOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('rothKatund','Roth-Katund','EasternDesolationUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ruinedCardolan','Ruined Cardolan','CardolanMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('RUNNING_FORD','Running Ford','DaleMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('runningStones','Running Stones','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ruryb','Ruryb','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ruverenni','Ruverenni','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('saavak','Saavak','MolraeenMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('saiae','Sa''iae','TaitaeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('saittaahc','Saittaahc','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('samudari','Samudari','UddariMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SANDHILL_TOWN','Lîpha-tûn','CoastSouthronMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SARN_FORD','Sarn Ford','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('sarndraraz','Sarndraraz','IronfistsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('saurrung','Saurrung','UddariMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SCARY','Scary','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SCATHA','Scatha''s Lair','GundabadOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('scuttledells','Scuttledells','GreenwoodElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('senyaw','Senyaw','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SEREGOST','Seregost','BlackUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('serpentsTeeth','Serpent''s Teeth','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SHADOW_POINT','Hardorogost','HalfTroll');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('shiningPort','Shining Port','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('shipwreckCove','Shipwreck Cove','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('silentPort','Silent Port','UddariMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('siyaek','Siyaek','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('sjon','Sjön','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('skjultoy','Skjultøy','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('skorghijl','Skorghijl','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('soltusk','Soltusk','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SOUTH_DESERT_TOWN','Izêm-ulzuz','HaradNomad');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SOUTH_DOWNS','South Downs','LonelandsRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SOUTH_DUNLAND','Firwold','DunlandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SOUTH_FOROCHEL','South Forochel','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('SOUTH_UNDEEP','South Undeep','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('springsOfNurn','Springs of Nurn','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('staaraxinai','Staaraxinai','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('STADDLE','Staddle','BreeHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('stiiless','Stiiless','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('STOCK','Stock','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('stomUtot','Stom-Utot','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('striikjnt','Striikjnt','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('strota','Strota','KaravaliMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('sudeing','Sudein''g','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('sunsetArch','Sunset Arch','ParaliakosMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('sunsetVale','Sunset Vale','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('swansLanding','swansLanding','EnedwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tadrorri','Tadrorri','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tahralia','Tahralia','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TARLANG','Tarlang''s Neck','BlackrootValeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TARNOST','Tarnost','DolAmrothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tarrondor','Tarrondor','HarondorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tartorum','Tartorum','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TAURELONDE','Taurelondë','ArAdunaimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('taurmorvith','Taur Morvith','DolGuldurOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('teheledir','Teheledir','NuriagMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('templeOfTheWind','Temple of the Wind','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('terrionu','terrionu','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('THARBAD','Tharbad','CardolanMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('THAURBAND','Thorband','NurnOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('THE_TROLLSHAWS','Trollshaws','RhudaurHillman');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theAbandonedPort','The Abandoned Port','QasinadrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theAngle','The Angle','DunedainRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theBlackArm','The Black Arm','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theBreak','The Break','LimwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theEasternBridge','The Eastern Bridge','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theEmeraldHall','The Emerald Hall','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theEntwash','The Entwash','EastfoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theFortOfTears','The Fort of Tears','NuriagMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theGreatInn','The Great Inn','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theGreenFord','The Green Ford','MolraeenMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theGroveOfRest','The Grove of Rest','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theLastSands','The Last Sands','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theLastStop','The Last Stop','ForochelOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('thelasttrail','The Last Trail','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theLostWoods','The Lost Woods','WainriderMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theNorthernPass','The Northern Pass','LhugathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theNorthlands','The Northlands','RhudaurHillman');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theOldCamp','The Old Camp','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theOldCavern','The Old Cavern','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theOldCity','The Old City','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theOldRuins','The Old Ruins','LogathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('thePerch','The Perch','LebenninMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('thePortOfDaggers','The Port of Daggers','ForochelOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theRedFord','The Red Ford','SargathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theRubooryMansion','The Ruboory Mansion','RuboorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theSmallDell','The Small Dell','RhovanionMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theSmallGate','The Small Gate','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theSouthernGate','The Southern Gate','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theStone','The Stone','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theTownOfGuard','The Town of Guard','SargathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theTownOfTheLake','The Town of the Lake','CuivienenElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theWhiteArm','The White Arm','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('theWindHalls','The Wind Halls','StonefootDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('THORIN_HALLS','Thorin''s Halls','BlueDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('THRAIN_HALLS','Thráin''s Halls','BroadbeamsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('THRANDUIL_HALLS','Thranduil''s Halls','WoodlandRealmElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tiaomu','Tiáomù','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tiar','Tiar','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tiazo','Tiazo','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TIGHFIELD','Tighfield','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tirdin','Tirdîn','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('titulCa','Titul Ca','ThoronriMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tofarvn','Töfarvn','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TOL_FUIN','Tol Fuin','SindarElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TOL_MORWEN','Tol Morwen','SindarElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TOLFALAS_ISLAND','Tolfalas','LebenninMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tolhithil','Tol Hithil','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('toloruuk','Tol Oruuk','HalfTroll');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('torerech','Tor-erech','WoodlandRealmElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('torhugal','Torhugal','RhudelMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('toromm','Toromm','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('torondahaz','Torondahaz','OrocarniDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TOWER_HILLS','Elostirion','MithlondElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TOWN_BONES','Town of Bones','SyyranniMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('traphel','Traphel','PinnathGelinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tratagaron','Tratagaron','MahuduinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TREEBEARD_HILL','Treebeard''s Hill','FangornEnt');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('treholm','Treholm','FangornEnt');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tremera','Tremera','TaurethrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('trevaari','Trevaari','AvariElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('trionkah','Trion-kah','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TROLL_ISLAND','Tol Torog','HalfTroll');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('troortor','Troortor','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('troraleen','Troraleen','MorwaithMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('trultolm','Trultolm','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tsama','Tsama','UsrakinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tsavat','Tsavat','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tselEliinaar','Tsel Eliinaar','HaradNomad');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tselKheremGol','Tsel Kherem Gol','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tselnahkGol','Tsel''nahk Gol','KhandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('tuburr','Tuburr','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('TUCKBOROUGH','Tuckborough','TookHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('twinWinds','Twin Winds','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('UDUN','Valley of Udûn','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('udunoroth','Udunoroth','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('uduzuur','Uduzuur ','UsrakinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('ugomlaan','Ugomlaan','ChelkarMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('uguunas','Uguunas','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('uliitbaarn','Uliitbaarn','ChelkarMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('UMBAR_CITY','Umbar','UmbarMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('UMBAR_GATE','Gate of Umbar','UmbarMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('umda','Umda','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('unaalili','Una-alili','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('unaxi','Unaxi','WickedDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('urggalog','Urggalag','MordorOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('URUK_HIGHLANDS','Uruk Highlands','IsengardUruk');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('utotNuriag','Utot Nuriag','NuriagMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('utovnor','Utovnor','LossothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('vaja_chor','Vaja Chor','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('vajaIsArra','Vajais Arra','NgoairuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('VALLEY_OF_SPIDERS','Valley of Spiders','NanUngolOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('valleyOfTheWind','Valley of the Wind','UddariMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WAYMEET','Waymeet','TookHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WEATHERTOP','Weathertop','LonelandsRanger');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('weiCaahn','Wei Caahn','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WELLINGHALL','Wellinghall','FangornEnt');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WEST_GATE','West Gate','EregionElf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WEST_PEAK','West Peak','IronHillsDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('westernCrossroads','Western Crossroads','LogathMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('westfold','Westfold','WestfoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('westruin','West Ruin','WestemnetMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('whiteMountainPass','White Mountain Pass','DunharrowMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WHITFURROWS','Whitfurrows','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('wienChi','Wein Chi','VsegoMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WILLOWBOTTOM','Willowbottom','ShireHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('windyCrossroads','Windy Crossroads','VarillesraDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WITHERED_HEATH','Withered Heath','GundabadOrc');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WITHYWINDLE_VALLEY','Withywindle Valley','BucklandHobbit');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WOLD','Woldhall','WoldMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('WULFBURG','Wulfburg','DunlandMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('xhiluCrossroads','Xhilu Crossroads','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('xhiziluKhu','Xhizilu''Khu','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('xiao','Xi''ao','WickedDwarf');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('xongWeii','Xong Wei''i','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('xoonUtu','Xoon-utu','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('xufhan','Xufhan','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('yahaban','Yahaban','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('yahlimiti','Yahlimiti','CerinrimMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('yatraha','Yatraha','TaiyobuMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('yetti','Yet-ti','ProshloyeMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('yongxingDao','Yongxing Dao','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('yorri','Yorri','ZunimlothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('yuanjiaao','Yuanjia''ao','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('yuiba','Yuiba','AenurinMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('zauHinor','Zau Hinor','BalchothMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('zhedi','Zhedi','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('zhengying','Zhengying','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('zizir','Zizir','RuboorMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('zorzarak','Zorzarak','CorsairOfUmbar');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('zueenli','Zueenli','JinzhunMan');
INSERT INTO waypoints (code, display_name, realm_code) VALUES ('zuun','Zuun','ZunimlothMan');
